### ISSUE TITLE
validate

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#13]
> Because the definition of contract and the definition of validate-rule have great similarity, the definition of contract in the current version will simply generate the corresponding validate-rule. The specific use of 'ctx.rule.' plus the Model name directly introduced .
> 
> The above model, you can use the following method when doing verification (use egg-validate)
> 
> `ctx.validate(ctx.rule.createResource, ctx.request.body);`

I understand that currently it is not ready for production for instance , see https://github.com/node-modules/parameter#string
When I set `format` as a regex value , it loose `test` method , As you do `JSON.parse(JSON.stringify(contract));`
https://github.com/Ysj291823/egg-swagger-doc/blob/master/lib/swagger_rule.js#L5

Why you do this?

**Comment by Ysj291823** [comment]
Contract is a referenced object. This is done to avoid modifications to the original object.

'When I set format as a regex value , it loose test method.' Because the current version does not support regex

**Comment by sm2017** [comment]
Ok
