### ISSUE TITLE
Default response

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#17]
Always we have a `default : successful operation` in response , It must be removed
![image](https://user-images.githubusercontent.com/19644997/47772773-03007b80-dcfd-11e8-8a49-73e4afae1ecb.png)

**Comment by sm2017** [comment]
@Ysj291823 , @mkc-yanshijie Can you fix it?

**Comment by Ysj291823** [comment]
I will remove it, if we has defined a response
