### ISSUE TITLE
multipart upload

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#24]
How can I document multipart upload?
https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by sm2017** [comment]
@Ysj291823 @mkc-yanshijie Reply please

**Comment by Ysj291823** [comment]
you can do it like this:

/**
 * @Summary 文件上传
 * @Router Get /v1/upload
 * @Request formData integer courseId 课程ID
 * @Request formData file *file
 * @Response 200 BaseResponse
 */

**Comment by sm2017** [comment]
@Ysj291823

the following works 
```js
/**

@summary 文件上传
@router Get /v1/upload
@request formData integer courseId 课程ID
@request formData file *file
@response 200 BaseResponse
*/
```

But what about 
```js
/**

@summary 文件上传
@router Get /v1/upload
@request formData MyCustomType courseId 课程ID
@request formData file *file
@response 200 BaseResponse
*/
```

How can we have `formData` with custom types? nit primitive types

**Comment by sm2017** [comment]
https://swagger.io/docs/specification/describing-request-body/multipart-requests/

**Comment by sm2017** [comment]
@Ysj291823 Do you have plan to support  OpenAPI 3 ?

**Comment by Ysj291823** [comment]
no, recently
