### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#29]
After my PR https://github.com/Ysj291823/egg-swagger-doc/pull/27 , unfortunately  you don't release a version and I see that you have huge changes and some releases
But I see that it is not currently stable and usable
When I can have a stable version?

**Comment by Ysj291823** [comment]
it is the endpoint, is there err log

**Comment by sm2017** [comment]
@Ysj291823 no error log , just 404 not found page when I open http://127.0.0.1:7001/swagger-ui.html

**Comment by Ysj291823** [comment]
you can see https://github.com/Ysj291823/egg-example-api ,  Are there any differences？

**Comment by Ysj291823** [comment]
i have meet the same problem, when upgrade the old version plugin to new. i will check it.

**Comment by Ysj291823** [comment]
you can try for it , i push a new version

**Comment by sm2017** [comment]
I tried version 2.1.5 , http://127.0.0.1:7001/swagger-ui.html is not works , Error 404

**Comment by sm2017** [comment]
>i have meet the same problem, when upgrade the old version plugin to new. i will check it.

I also test it in fresh project

**Comment by sm2017** [comment]
> you can see https://github.com/Ysj291823/egg-example-api , Are there any differences？

I clone egg-example-api and remove https://github.com/Ysj291823/egg-swagger-doc/blob/master/package.json#L27-L29 as I use node 10.14.2

http://localhost:7001/swagger-ui.html works!!!! Why?

**Comment by sm2017** [comment]
I found that you add enable option default is false
