### ISSUE TITLE
ts不支持

### ISSUE THREAD

**Issue by hcxw11** [Ysj291823/egg-swagger-doc#3]
用ts的话，后缀是ts，我看了下扫描里面写死了扫描后缀为.js的文件，能不能加一个配置项，默认为扫描.js，但是可以配置为扫描其他的后缀
![image](https://user-images.githubusercontent.com/16369309/42925383-985ef858-8b60-11e8-84bb-63114d861002.png)

**Comment by Ysj291823** [comment]
其实开始是为了JS项目写的, TS的话我记得有个修饰器版 koa-swagger-decorator ，虽然不是egg插件但是应该完全够用，就没有往这个去弄了。有空的话我会加上的

**Comment by hcxw11** [comment]
@Ysj291823 👌谢谢
