### ISSUE TITLE
npm run test 404

### ISSUE THREAD

**Issue by YL2014** [Ysj291823/egg-swagger-doc#36]
hello，项目clone下来后，跑`npm run test`跑不通，`/swagger-ui.html`和`/swagger-doc`都404，需要做什么操作吗

**Comment by Ysj291823** [comment]
更新了插件版本，你可以重新拉一下

**Comment by Ysj291823** [comment]
忘记了，默认配置里enable是 false，不是true

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: YL <notifications@github.com>
发送时间: Wednesday, January 23, 2019 11:26:14 AM
收件人: Ysj291823/egg-swagger-doc
抄送: Aris.J; Comment
主题: Re: [Ysj291823/egg-swagger-doc] npm run test 404 (#36)


更新了插件版本，你可以重新拉一下

还是不行呢

1. clone

2. npm install

3. npm run test-local



结果如下

> egg-swagger-doc@2.2.2 test-local /Users/yl/test/egg-swagger-doc

> egg-bin test







  test/swagger-doc.test.js

    1) should GET /swagger-ui.html

    2) should GET /swagger-doc





  0 passing (815ms)

  2 failing



  1) test/swagger-doc.test.js

       should GET /swagger-ui.html:

     Error: expected 200 "OK", got 404 "Not Found"

      at process._tickCallback (internal/process/next_tick.js:180:9)

      [use `--full-trace` to display the full stack trace]



  2) test/swagger-doc.test.js

       should GET /swagger-doc:

     Error: expected 200 "OK", got 404 "Not Found"

      at process._tickCallback (internal/process/next_tick.js:180:9)

      [use `--full-trace` to display the full stack trace]







⚠️  Error: /Users/yl/test/egg-swagger-doc/node_modules/egg-bin/node_modules/mocha/bin/_mocha --require=/Users/yl/test/egg-swagger-doc/node_modules/egg-bin/lib/mocha-clean.js,--require=/Users/yl/test/egg-swagger-doc/node_modules/co-mocha/lib/co-mocha.js,--require=/Users/yl/test/egg-swagger-doc/node_modules/intelli-espower-loader/intelli-espower-loader.js,--timeout=60000,--exit,test/swagger-doc.test.js exit with code 2

⚠️  Command Error, enable `DEBUG=common-bin` for detail

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! egg-swagger-doc@2.2.2 test-local: `egg-bin test`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the egg-swagger-doc@2.2.2 test-local script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/yl/.npm/_logs/2019-01-23T03_21_12_832Z-debug.log



环境如下

mac

node v8.11.2

**Comment by Ysj291823** [comment]
fixed, please config the plugin enable
