### ISSUE TITLE
operationId undefined

### ISSUE THREAD

**Issue by sm2017** [Ysj291823/egg-swagger-doc#39]
Why my operationId is like `controller-myTag-undefined` ?

**Comment by Ysj291823** [comment]
it has been fixed in new version

**Comment by sm2017** [comment]
@Ysj291823 I upgrade to  egg-swagger-doc@2.2.3 , not fixed

**Comment by sm2017** [comment]
@Ysj291823 I run in debug mode

I understand that https://github.com/Ysj291823/egg-swagger-doc/blob/master/lib/document/index.js#L126 is wrong

You have `blocks` , I understand that `blocks` contains my JSDocs also
I have

```js
/**
* @type string
**/
```

In my code too and `blocks` contains these codes

In my debug , blocks.length is 14 but func.length is 6 , So , func[i - 1] is undefined when i is greater than 6

**Comment by sm2017** [comment]
To reproduce issue
Clone and run https://github.com/sm2017/egg-example-api

As you can see in my commit https://github.com/sm2017/egg-example-api/commit/29c408570ab25515e424a10425bd3fcd349943dd I just add some JSdoc

**Comment by Ysj291823** [comment]
Oh, it is bad, I need make blocks specific

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: sm2017 <notifications@github.com>
发送时间: Saturday, January 26, 2019 3:47:07 PM
收件人: Ysj291823/egg-swagger-doc
抄送: Aris.J; Mention
主题: Re: [Ysj291823/egg-swagger-doc] operationId undefined (#39)


@Ysj291823<https://github.com/Ysj291823> I run in debug mode

I understand that https://github.com/Ysj291823/egg-swagger-doc/blob/master/lib/document/index.js#L126 is wrong

You have blocks , I understand that blocks contains my JSDocs also
I have

/**
* @type string
**/

In my code too and blocks contains these codes

In my debug , blocks.length is 14 but func.length is 6 , So , func[i - 1] is undefined when i is greater than 6

―

**Comment by Ysj291823** [comment]
it has been fixed 2.2.4

**Comment by Ysj291823** [comment]
my fault.  update to the latest. try it please

**Comment by Ysj291823** [comment]
remove the lock.json

**Comment by sm2017** [comment]
Fixed! thanks a lot

**Comment by sm2017** [comment]
@Ysj291823 undefined issue is fixed , bur we have some bugs , I will try to show you how to reproduce it

**Comment by Ysj291823** [comment]
If it is not a function with router, we need make a comment like this

/**
* @ignore
*/

To skip the function

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: sm2017 <notifications@github.com>
发送时间: Wednesday, January 30, 2019 5:30:10 PM
收件人: Ysj291823/egg-swagger-doc
抄送: Aris.J; Mention
主题: Re: [Ysj291823/egg-swagger-doc] operationId undefined (#39)


See sm2017/egg-example-api@737d364<https://github.com/sm2017/egg-example-api/commit/737d3648f310f38e028b778e4560375f62c46835>

controller-user-_myPrivateFunction is wrong!! it is used for POST /v1/users

git clone https://github.com/sm2017/egg-example-api.git
cd egg-example-api
yarn upgrade egg-swagger-doc --latest
yarn run dev

―

**Comment by Ysj291823** [comment]
In  userController ， there is an example

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 严 世杰 <ysj291823@outlook.com>
发送时间: Wednesday, January 30, 2019 7:23:22 PM
收件人: Ysj291823/egg-swagger-doc; Ysj291823/egg-swagger-doc
抄送: Mention
主题: 答复: [Ysj291823/egg-swagger-doc] operationId undefined (#39)

If it is not a function with router, we need make a comment like this

/**
* @ignore
*/

To skip the function

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: sm2017 <notifications@github.com>
发送时间: Wednesday, January 30, 2019 5:30:10 PM
收件人: Ysj291823/egg-swagger-doc
抄送: Aris.J; Mention
主题: Re: [Ysj291823/egg-swagger-doc] operationId undefined (#39)


See sm2017/egg-example-api@737d364<https://github.com/sm2017/egg-example-api/commit/737d3648f310f38e028b778e4560375f62c46835>

controller-user-_myPrivateFunction is wrong!! it is used for POST /v1/users

git clone https://github.com/sm2017/egg-example-api.git
cd egg-example-api
yarn upgrade egg-swagger-doc --latest
yarn run dev

―
