### ISSUE TITLE
the type of response parameter does not exit

### ISSUE THREAD

**Issue by chanmufeng** [Ysj291823/egg-swagger-doc#5]
`class AccountController extends Controller {
    /**
     * @Router POST /login
     * @Response 0 body test
     * @Summary 登录接口
     */
    async login() {
        const { ctx, app, config } = this;
        const name = ctx.request.body.name;
        const password = ctx.request.body.password;

        const user = await app.mysql.get('user', {
            name,
        });

        if (!user || ctx.helper.md5(password) !== user.password) {
            ctx.body = ctx.ResultUtil.error(config.werror.ERR_ACCOUNT_LOGIN);
            return;
        }

        const userJSON = JSON.stringify(user);
        const token = app.jwt.sign(userJSON, app.config.jwt.secret);

        ctx.body = ctx.ResultUtil.success({ user, token });
    }
}`

错误信息如下：
 nodejs.Error: [egg-swagger-doc] error at post:/login ,the type of response parameter does not exit
    at module.exports.app (E:\node\op-new\op-new-admin\node_modules\egg-swagger-doc\lib\swagger_loader.js:122:23)
    at app.beforeStart (E:\node\op-new\op-new-admin\node_modules\egg-swagger-doc\app.js:11:21)
    at Object.callFn (E:\node\op-new\op-new-admin\node_modules\egg-core\lib\utils\index.js:36:42)
    at process.nextTick (E:\node\op-new\op-new-admin\node_modules\egg-core\lib\egg.js:226:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

把@Response注释去掉就可以了，，这是为什么？怎么处理？

**Comment by Ysj291823** [comment]
@Response {HttpStatus} {Type} {Description}     状态码 返回值类型 描述

这里是因为没有在contract中找到body的定义

**Comment by Ysj291823** [comment]
Type 也可以是基础类型

**Comment by Ysj291823** [comment]
Type 可以是基础类型，当不是基础类型的时候，就会contract中自己定义的object中去找 ，没有找到就会报着个错了

**Comment by showerc** [comment]
* @Request body string access_token test 一样报错。

查询lib\swagger_loader.js:204 - 211 
得知，第一个参数等于body的情况下，第二个参数只能为array或者已经在contract中定义的对象。
而不能是string等其他基础类型，否则会
        throw new Error(`[egg-swagger-doc] error at ${routers[0][1].toLowerCase()}:${routers[0][2]} ,the type of request parameter does not exit`);
另外求contract定义对象的格式或者示例啊，谢谢了

**Comment by Ysj291823** [comment]
@request body string access_token test 一样报错。这个是个bug,现在的逻辑只针对了body是自定义object的时候做了处理，我这两天优化下

**Comment by Ysj291823** [comment]
建议body中如果是基础类型的话，用body用formData 替代

**Comment by DuJiming** [comment]
```js
  /**
   * @summary 登录
   * @description 登录
   * @router post /api/auth
   * @request body userLoginTransfer *body
   * @response 200 authResponse 登录成功
   * @response 401 string 登录失败
   */
```
```txt
error at post:/api/auth ,the type of response parameter does not exit
```
我写了string，也报错呢

**Comment by DuJiming** [comment]
> ```js
>   /**
>    * @summary 登录
>    * @description 登录
>    * @router post /api/auth
>    * @request body userLoginTransfer *body
>    * @response 200 authResponse 登录成功
>    * @response 401 string 登录失败
>    */
> ```
> 
> ```
> error at post:/api/auth ,the type of response parameter does not exit
> ```
> 
> 我写了string，也报错呢

我知道了，原来是只支持body类型，我理解成跟request Type一样了
