### ISSUE TITLE
用了这个插件，public目录就失效了 

### ISSUE THREAD

**Issue by guchenhui** [Ysj291823/egg-swagger-doc#7]

**Comment by guchenhui** [comment]
能不能将swaggerui所在的目录设置成egg默认的public目录？

**Comment by guchenhui** [comment]
能不能将swaggerui所在的目录设置成egg默认的public目录？

**Comment by okoala** [comment]
@guchenhui  可以用这个版本
https://github.com/okoala/egg-swagger-doc2

**Comment by Ysj291823** [comment]
学习学习，我也再研究下
